api_platform:
    title:  API Platform
    version: 1.0.0
    description: API Platform
    # Mercure integration, remove if unwanted
    #metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
