framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages:
                            binding_keys: [messages]
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000

            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages_high
                        type: direct
                    queues:
                        messages_high:
                            binding_keys: [high]
                retry_strategy:
                    max_retries: 5
                    delay: 500
                    multiplier: 2

            emails:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: emails
                        type: direct
                    queues:
                        emails:
                            binding_keys: [emails]
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 2
                    max_delay: 120000

            failed: 'doctrine://default?queue_name=failed'
            
            # Синхронный транспорт (для тестов)
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: emails
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\SendOrderConfirmationEmail: emails
            App\Message\SendOrderStatusChangedEmail: emails

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                async_priority_high: 'in-memory://'
                emails: 'in-memory://'
                failed: 'in-memory://'
