version: '3'
networks:
  irish-network:
    driver: bridge

services:
  php:
    container_name: php_irish
    environment:
      - PHP_IDE_CONFIG=serverName=XdebugServer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/irish
    depends_on:
      - mysql
    networks:
      - irish-network

  mysql:
    image: mysql:8
    container_name: mysql_irish
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - irish-network

  nginx:
    container_name: nginx_irish
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/irish
    #  - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #  - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - irish-network